name: Extract and release build artifact

# Note: This event will only trigger a workflow run
# if the workflow file is on the default branch
# - So we need to run this workflow explicitly again
# after the container are pushed to the registry
#on:
#  workflow_run:
#    workflows: ["Build and release container"]
#    branches: '**'
#    types:
#      - completed

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  extract-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Extract build artifact from build container
      uses: bbusse/actions-docker-extract@latest
      id: extract_amd64
      with:
        image: "ghcr.io/bbusse/matcha-build:latest"
        path: "tmp/matcha.tar.xz"
        platform: linux/amd64

    - name: Extract build artifact from build container
      uses: bbusse/actions-docker-extract@latest
      id: extract_htdocs
      with:
        image: "ghcr.io/bbusse/matcha-build:latest"
        path: "tmp/matcha-htdocs.tar.xz"
        platform: linux/amd64

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        title: matcha
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "latest"
        files: |
          ${{ steps.extract_amd64.outputs.destination }}/matcha.tar.xz
          ${{ steps.extract_htdocs.outputs.destination }}/matcha-htdocs.tar.xz
